services:
  - type: web
    name: tv-binance-bot
    env: python
    repo: https://github.com/Sergey427/tv-binance-bot
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
